[versions]
# libraries
jsoup = "1.17.2"
dbutils = "1.8.1"
mp3spi = "1.9.5.4"
ideaCompat = "0.0.4"
junit = "4.13.2"
websocket = "1.5.6"

# plugins
kotlin = "1.9.24"
kover = "0.8.0"
changelog = "2.2.0"
gradleIntelliJPlugin = "1.17.3"

[libraries]
jsoup = { group = "org.jsoup", name = "jsoup", version.ref = "jsoup" }
dbutils = { group = "commons-dbutils", name = "commons-dbutils", version.ref = "dbutils" }
mp3spi = { group = "com.googlecode.soundlibs", name = "mp3spi", version.ref = "mp3spi" }
ideaCompat = { group = "com.github.YiiGuxing", name = "intellij-idea-compat", version.ref = "ideaCompat" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
websocket = { group = "org.java-websocket", name = "Java-WebSocket", version.ref = "websocket" }

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
gradleIntelliJPlugin = { id = "org.jetbrains.intellij", version.ref = "gradleIntelliJPlugin" }
