[versions]
# libraries
jsoup = "1.22.1"
dbutils = "1.8.1"
mp3spi = "1.9.5.4"
junit = "4.13.2"
websocket = "1.6.0"

# plugins
# Warning: Kotlin plugin 2.2.x is incompatible and will result in a startup crash
# (NoClassDefFoundError: kotlin/coroutines/jvm/internal/SpillingKt in ProjectActivity).
# Please upgrade only when compiling against a compatible version of IDEA.
kotlin = "2.1.21"
kover = "0.9.4"
changelog = "2.5.0"
gradleIntelliJPlugin = "1.17.4"

[libraries]
jsoup = { group = "org.jsoup", name = "jsoup", version.ref = "jsoup" }
dbutils = { group = "commons-dbutils", name = "commons-dbutils", version.ref = "dbutils" }
mp3spi = { group = "com.googlecode.soundlibs", name = "mp3spi", version.ref = "mp3spi" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
websocket = { group = "org.java-websocket", name = "Java-WebSocket", version.ref = "websocket" }

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
gradleIntelliJPlugin = { id = "org.jetbrains.intellij", version.ref = "gradleIntelliJPlugin" }
