blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions
    url: https://github.com/YiiGuxing/TranslationPlugin/discussions
    about: Use GitHub discussions for message-board style questions and discussions.
  - name: 提问与讨论
    url: https://github.com/YiiGuxing/TranslationPlugin/discussions
    about: 如果您需要提问或者开始一场讨论，请使用 GitHub Discussions。