
name: Issues

on:
  issues:
    types: [opened, labeled]

permissions:
  issues: write

jobs:

  label:
    name: Label Issue
    if: github.event.action == 'opened'
    runs-on: ubuntu-latest
    steps:

      - name: Fetch Sources
        uses: actions/checkout@v3

      - name: Label Issue
        uses: Videndum/super-labeler-action@1.1.0
        with:
          GITHUB_TOKEN: "${{ secrets.ISSUE_LABEL_TOKEN }}"


  comment:
    name: Comment On Issue
    if: github.event.action == 'labeled'
    runs-on: ubuntu-latest
    steps:

      - name: Comment
        if: github.event.label.name == 'dynamic plugin :electric_plug:'
        uses: ben-z/actions-comment-on-issue@1.0.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          message: >
            This problem is caused by the dynamic loading of the plugin, you need to restart the IDE to solve it.


  close:
    name: Close Issue
    if: github.event.action == 'labeled'
    runs-on: ubuntu-latest
    steps:

      - name: Close Fixed
        if: github.event.label.name == 'fixed :hammer:'
        uses: YiiGuxing/close-issue@v2.1.0

      - name: Close duplicate
        if: github.event.label.name == 'duplicate'
        uses: YiiGuxing/close-issue@v2.1.0
        with:
          close-reason: not_planned

      - name: Close As `not plugin's bug`
        if: github.event.label.name == 'not plugin''s bug'
        uses: YiiGuxing/close-issue@v2.1.0
        with:
          close-reason: not_planned
          comment: >
            This issue has been automatically closed because it is not an issue for this project.
            If you think there are something really wrong, please reply this issue. Thanks for your cooperation.

      - name: Close As `wontfix`
        if: github.event.label.name == 'wontfix'
        uses: YiiGuxing/close-issue@v2.1.0
        with:
          close-reason: not_planned
          comment: >
            This issue has been automatically closed as `wontfix` because nothing it's wrong here.
            If you think there are something really wrong, please reply this issue. Thanks for your cooperation.
